### ISSUE TITLE
Support for IFC file with UTF-8 BOM

### ISSUE THREAD

**Issue by thbeu** [IfcOpenShell/step-file-parser#5]
IFC file with UTF-8 BOM results in lark.exceptions.UnexpectedCharacters,

**Comment by aothms** [comment]
I know this is a surprising answer in 2024, but IFC uses ISO 10303-21:2002 in which any non-ascii character (outside of the 0x20-0x7e range) is invalid. So the parser is behaving correctly in marking this as invalid.

(The 2016 edition of ISO 10303-21, which IFC does not use, is unicode-aware (but I'm not exactly sure what it says about byte order marks).)

**Comment by thbeu** [comment]
I am just wondering because the bS IFC example files have an UTF-8 BOM, for example: https://github.com/buildingSMART/IFC/blob/776c6d92a3674bc8a5b371061a40a09a4e6b8354/Examples/Building%20element%20elemented%20case/Examples/Wall%20elemented%20case/File.ifc

**Comment by aothms** [comment]
There is a lot of repositories floating around unfortunately, but the most recent version of the files is being maintained here https://github.com/buildingSMART/IFC4.3.x-sample-models/tree/main/models

**Comment by thbeu** [comment]
Thanks for clarifying.
